package org.jbpm.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class MedicalEntry  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String code;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date date;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String description;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer id;

    public MedicalEntry() {
    }

    public MedicalEntry(java.lang.Integer id, java.util.Date date, java.lang.String code, java.lang.String description) {
        this.id = id;
        this.date = date;
        this.code = code;
        this.description = description;
    }


    
    public java.lang.String getCode() {
        return this.code;
    }

    public void setCode(  java.lang.String code ) {
        this.code = code;
    }
    
    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(  java.util.Date date ) {
        this.date = date;
    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(  java.lang.String description ) {
        this.description = description;
    }
    
    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(  java.lang.Integer id ) {
        this.id = id;
    }
}