package org.jbpm.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Patient  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date birthdate;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String gender;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String lastname;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;

    public Patient() {
    }

    public Patient(java.lang.String name, java.lang.String lastname, java.util.Date birthdate, java.lang.String gender) {
        this.name = name;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.gender = gender;
    }


    
    public java.util.Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(  java.util.Date birthdate ) {
        this.birthdate = birthdate;
    }
    
    public java.lang.String getGender() {
        return this.gender;
    }

    public void setGender(  java.lang.String gender ) {
        this.gender = gender;
    }
    
    public java.lang.String getLastname() {
        return this.lastname;
    }

    public void setLastname(  java.lang.String lastname ) {
        this.lastname = lastname;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(  java.lang.String name ) {
        this.name = name;
    }
}